version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: .devcontainer/Dockerfile
    environment:
      - TEST_HOST=host.docker.internal
      - TEST_PORT=7777
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
